language: python
python:
  - "3.5"
  - "3.6"

install:
  - "pip install pipenv"
  - "pipenv --three"
  - "pipenv install"
  - "pipenv graph"

script:
  # Execute tests under the 'tests' directory.
  - python -m pytest --cov=tests/

after_success:
  - codecov
