language: python
python:
  - "3.5"
  - "3.6"

install:
  - "pip install --upgrade pytest-cov pytest"
  - "pip install codecov"
  - "pip list"

script:
  # Execute tests under the 'tests' directory.
  - py.test --cov=./ tests/
  - codecov

after_success:
  - codecov
