language: python
python:
  - "3.6"
  - "3.7"

install:
  - "pip install pipenv"
  - "pipenv --three"
  - "pipenv install"
  - "pipenv graph"

script:
  # Execute tests under the 'tests' directory.
  - python -m pytest

after_success:
  - codecov
